apiVersion: gcm.vmware.com/v1alpha1
kind: ManagedCluster
metadata:
  name: gcm-cluster-02
spec:
  topology:
    controlPlane:
      count: 1
      class: guaranteed-xsmall
      storageClass: vsan-default-storage-policy
    workers:
      count: 2
      class: guaranteed-xsmall
      storageClass: vsan-default-storage-policy
  distribution:
    version: v1.15.5+vmware.1.66-guest.1.26
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
